# NumPy

In [2]:
import numpy
n = numpy.arange(27)

In [6]:
n.reshape(3, 3, 3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [13]:
m = numpy.asarray([[123,12,123,12,33],[2,3,4,5,6],[3,4,5,6,7]])
type(m)

numpy.ndarray

# Convert images to NumPy arrays

In [12]:
import cv2

In [15]:
# Reading image in grayscale
im_grayscale = cv2.imread('smallgray.png', 0)
im_grayscale

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [16]:
# Reading image in BGR (conventionally RGB)
im_bgr = cv2.imread('smallgray.png', 1)
im_bgr

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [17]:
cv2.imwrite('new_smallgray.png', im_grayscale)

True

# Indexing, Slicing, and Iterating NumPy Arrays

In [18]:
im_grayscale

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [25]:
im_grayscale[2, 1]

134

In [23]:
im_grayscale[0:2, 2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [26]:
for row in im_grayscale:
    print(row)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [27]:
for col in im_grayscale.T:
    print(col)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [28]:
for val in im_grayscale.flat:
    print(val)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


# Stacking & Splitting NumPy Arrays

In [30]:
# Requires a tuple of arrays to be stacks (1 positional argument only)
ims = numpy.hstack((im_grayscale, im_grayscale))